# Generated by Django 3.2.8 on 2022-06-30 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accomodation',
            new_name='Accommodation',
        ),
    ]
